// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umsztflayqrghaqtxnnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtc3p0ZmxheXFyZ2hhcXR4bm5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxOTkyNDcsImV4cCI6MjA3Mjc3NTI0N30.1tsG_JyYIQluw0YWCJSHhysfOX1TGQIv_jyhgUASSTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});